EcommerceWeb/Controllers/RolesController.cs
using EcommerceWeb.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EcommerceWeb.Controllers
{
    public class RolesController : Controller
    {
        ApplicationDbContext context;

        public RolesController()
        {
            context = new ApplicationDbContext();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var Roles = context.Roles.ToList();
            return View(Roles);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            var Role = new IdentityRole();
            return View(Role);   
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Create(IdentityRole Role)
        {
            context.Roles.Add(Role);
            context.SaveChanges();
            return RedirectToAction("Index");
        }


        



    }
}

EcommerceWeb/Controllers/UserListController.cs
using EcommerceWeb.Models;
using EcommerceWeb.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EcommerceWeb.Controllers
{
    public class UserListController : Controller
    {

        ApplicationDbContext context;
        //Added
        public UserListController()
        {
            context = new ApplicationDbContext();
        }

        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        // GET: UserList
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            using (var db = new ApplicationDbContext())
            {
                var model = (from users in db.Users
                             select new
                             {
                                 UserId = users.Id,
                                 Email = users.Email,
                                 RoleNames = (from userRole in users.Roles
                                              join role in db.Roles on userRole.RoleId
                                              equals role.Id
                                              select role.Name).ToList()
                             }).ToList().Select(p => new UserIndexViewModel()
                             {
                                 UserId = p.UserId,
                                 Email = p.Email,
                                 UserRoles = string.Join(",", p.RoleNames)
                             });
                return View(model);
            }
        }


        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string id)
        {
            var model = new UserCRUDViewModel();
            var user = UserManager.FindById(id);
            using (var db = new ApplicationDbContext())
            {
                model.UserId = user.Id;
                model.Email = user.Email;
                model.UserName = user.UserName;
                model.UserRoles = UserManager.GetRoles(user.Id).SingleOrDefault();
                model.AvailableUsers = new List<SelectListItem>();

                foreach (var item in db.Roles)
                {
                    model.AvailableUsers.Add(new SelectListItem { Value = item.Name, Text = item.Name });
                }

                return View(model);
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(UserCRUDViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            using (var db = new ApplicationDbContext())
            {
                var user = UserManager.FindById(model.UserId);
                user.Id = model.UserId;

                UserManager.RemoveFromRole(user.Id, model.UserRoles);
                UserManager.AddToRole(user.Id, model.UserDropDown);

                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }



    }
}

EcommerceWeb/Views/Roles/AssignRoleToUser.cshtml
@*@model Microsoft.AspNet.Identity.EntityFramework.IdentityUser*@
@{
    ViewBag.Title = "AssignRoleToUser";
}

<h2>AssignRoleToUser</h2>

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.Label("Select your user type", new {@class= "col-md-2 control-lable "})
        <div class="col-md-10">
            @Html.DropDownList("UserName")
        </div>
    </div>
    <input type="submit" value="Create Role" style="background-color:lightgreen" />
}

EcommerceWeb/Views/Roles/Create.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    <table class="table">
        <tr>
            <td>Create a role</td>
            <td>
                @Html.EditorFor(m => m.Name)
            </td>
        </tr>

    </table>
    <input type="submit" value="Save" style="background-color:lightgreen" />
}

EcommerceWeb/Views/Roles/Edit.cshtml
@model EcommerceWeb.Models.ApplicationUser
@using (Html.BeginForm())
{
    @*@Html.HiddenFor(model => model.Id)*@
    <p>UserName:@Html.EditorFor(model => model.UserName)</p>
    <p>PhoneNumber:@Html.EditorFor(model => model.PhoneNumber)</p>
    <p>Email:@Html.EditorFor(model => model.Email)</p>
    <input type="submit" />
}

EcommerceWeb/Views/Roles/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
}
<h2>Available roles</h2>
@if (Request.IsAuthenticated)
{
    <table>@Html.ActionLink("Create Role", "Create", "Roles")</table>
    <table>@Html.ActionLink("See Users", "Index", "UserList")</table>


    <table>@Html.ActionLink("Create a user", "Register", "Account")</table>
}

    <table class="table table-bordered table-hover">
        <tr>
            <th>Role Name</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Name
                </td>
            </tr>
        }
    </table>

EcommerceWeb/Views/Roles/Users.cshtml
@model IEnumerable<EcommerceWeb.Models.ApplicationUser>
@{
    ViewBag.Title = "UserList";
}
<style>
    th, td {
        text-align: center;
    }
</style>
<h2>UserList</h2>
<table>
    <tr>
        <th>@Html.DisplayName("UserName")</th>
        <th>@Html.DisplayName("Email")</th>
        <th></th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(model => item.UserName)</td>
            <td>@Html.DisplayFor(model => item.Email)</td>
            <td>@Html.DisplayFor(model => item.Roles)</td>
            <td>@Html.ActionLink("Delete", "UserDelete", new { id = item.Id })</td>
            <td>@Html.ActionLink("Edit", "UserEdit", new { id = item.Id })</td>
        </tr>
    }
</table>